force-app/main/default/objects/Dossier__c/Dossier__c.object-meta.xml
<CustomObject>
    <label>Dossier</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>N° de Dossier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dossiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dossier__c/fields/Agence_bancaire__c.field-meta.xml
<CustomField>
    <fullName>Agence_bancaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agence bancaire</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dossiers (Agence bancaire)</relationshipLabel>
    <relationshipName>DossiersAgenceBancaire</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Banque__c.field-meta.xml
<CustomField>
    <fullName>Banque__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banque</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dossiers (Banque)</relationshipLabel>
    <relationshipName>Dossiers_Banque</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Banquier__c.field-meta.xml
<CustomField>
    <fullName>Banquier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banquier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dossiers (Banquier)</relationshipLabel>
    <relationshipName>DossiersBanquier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/CANEVAS_GENERE__c.field-meta.xml
<CustomField>
    <fullName>CANEVAS_GENERE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CANEVAS GENERE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/CanevasGeneratedBy__c.field-meta.xml
<CustomField>
    <fullName>CanevasGeneratedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CanevasGeneratedBy</label>
    <referenceTo>User</referenceTo>
    <relationshipName>GenerateCanevas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/contact__c.field-meta.xml
<CustomField>
    <fullName>contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Dossiers</relationshipLabel>
    <relationshipName>Dossiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Date_depot_dossier__c.field-meta.xml
<CustomField>
    <fullName>Date_depot_dossier__c</fullName>
    <label>Date dépôt dossier</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Date_du_premier_CANEVAS__c.field-meta.xml
<CustomField>
    <fullName>Date_du_premier_CANEVAS__c</fullName>
    <label>Date du premier CANEVAS</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Prospect_ou_Client_V_A_V_de_la_banque__c.field-meta.xml
<CustomField>
    <fullName>Prospect_ou_Client_V_A_V_de_la_banque__c</fullName>
    <label>Prospect ou Client V.A.V de la banque</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Simulation__c.field-meta.xml
<CustomField>
    <fullName>Simulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Simulation</label>
    <referenceTo>Simulation__c</referenceTo>
    <relationshipLabel>Dossiers</relationshipLabel>
    <relationshipName>Dossiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Super_banquier__c.field-meta.xml
<CustomField>
    <fullName>Super_banquier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Super banquier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dossiers (Super banquier)</relationshipLabel>
    <relationshipName>Dossiers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/VILLE_BANQUE__c.field-meta.xml
<CustomField>
    <fullName>VILLE_BANQUE__c</fullName>
    <label>VILLE BANQUE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casablanca</fullName>
            </value>
            <value>
                <fullName>Rabat</fullName>
            </value>
            <value>
                <fullName>Mohammedia</fullName>
            </value>
            <value>
                <fullName>Marrakesh</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Agadir</fullName>
            </value>
            <value>
                <fullName>Kenitra</fullName>
            </value>
            <value>
                <fullName>Fes</fullName>
            </value>
            <value>
                <fullName>Oujda</fullName>
            </value>
            <value>
                <fullName>Temara</fullName>
            </value>
            <value>
                <fullName>El Jadida</fullName>
            </value>
            <value>
                <fullName>Tanger</fullName>
            </value>
            <value>
                <fullName>Tetouan</fullName>
            </value>
            <value>
                <fullName>Nador</fullName>
            </value>
            <value>
                <fullName>TanTan</fullName>
            </value>
            <value>
                <fullName>Meknes</fullName>
            </value>
            <value>
                <fullName>Essaouira</fullName>
            </value>
            <value>
                <fullName>Al Hoceima</fullName>
            </value>
            <value>
                <fullName>Beni Mellal</fullName>
            </value>
            <value>
                <fullName>Settat</fullName>
            </value>
            <value>
                <fullName>Khribga</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SavePLContact.cls
public with sharing class SavePLContact {

    public Dossier__c dossier {get; set;}
    public Contact contact {get; set;}

    public SavePLContact(ApexPages.StandardController stdCtrl) {
        //Dossier
        dossier = (Dossier__c) stdCtrl.getRecord();

        if (dossier != NULL) {
            dossier = [SELECT Id, Contact__c, Banque__r.name,name, Simulation__c,
                       Agence_bancaire__r.name, VILLE_BANQUE__c, Super_banquier__r.Name,
                       Banquier__r.Name, Prospect_ou_Client_V_A_V_de_la_banque__c, Date_depot_dossier__c,CANEVAS_GENERE__c,Date_du_premier_CANEVAS__c,
                       (SELECT Id FROM Attachments WHERE Name LIKE '%DossierClient__%')
                       FROM Dossier__c WHERE Id = : dossier.Id];
            contact = [SELECT Id, Name FROM Contact WHERE Id = : dossier.Contact__c];
        }

    }

    //SAVE PDF
    public PageReference saveDossier() {
        PageReference pdf = Page.VF_PrintPLContact;
        pdf.getParameters().put('id', ApexPages.currentPAge().getParameters().get('id'));

        /*Attachment attach = new Attachment();
        Blob body;

        try {
            body = pdf.getContent();
        } catch (VisualforceException e) {
            body = Blob.valueOf('Some Text');
        }

        Integer version = dossier.Attachments.size() + 1;

        attach.Body = body;
        attach.Name = 'Meilleurcreditimmo_' +dossier.Banque__r.name+'_'+dossier.name+'_'+ contact.name + '.pdf';
        attach.IsPrivate = false;
        attach.ParentId = dossier.Id;

        insert attach;
        if(dossier.CANEVAS_GENERE__c == false && dossier.Date_du_premier_CANEVAS__c == null){
            dossier.CANEVAS_GENERE__c = true;
            dossier.Date_du_premier_CANEVAS__c = datetime.now();
            dossier.CanevasGeneratedBy__c = UserInfo.getUserId();
            update dossier;
        }

        return new PageReference('/' + attach.Id);*/
        
        ContentVersion cv = new ContentVersion();
        cv.ContentLocation = 'S'; 
        cv.PathOnClient = 'Meilleurcreditimmo_' + dossier.Banque__r.name +'_'+dossier.name+'_'+ contact.name + '.pdf';
        cv.Origin = 'H';
        cv.Title =  'Meilleurcreditimmo_' +dossier.Banque__r.name+'_'+dossier.name+'_'+ contact.name + '.pdf';
        cv.VersionData = Test.isRunningTest() ? Blob.valueOf('Hello') : pdf.getContentAsPDF(); 
        insert cv;
        
        cv = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =: cv.Id];
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = cv.ContentDocumentId;
        cdl.LinkedEntityId = dossier.Id ;
        cdl.ShareType = 'I';
        cdl.Visibility = 'AllUsers';
        insert cdl;
        
		return new PageReference('/' + dossier.Id);
    }


}