force-app/main/default/objects/Dossier__c/Dossier__c.object-meta.xml
<CustomObject>
    <label>Dossier</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>N° de Dossier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dossiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dossier__c/fields/Date_accord_dossier__c.field-meta.xml
<CustomField>
    <fullName>Date_accord_dossier__c</fullName>
    <label>Date Accord</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Date_d_p_t_facture__c.field-meta.xml
<CustomField>
    <fullName>Date_d_p_t_facture__c</fullName>
    <label>Date dépôt facture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Date_deblocage__c.field-meta.xml
<CustomField>
    <fullName>Date_deblocage__c</fullName>
    <label>Date Déblocage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Date_depot_dossier__c.field-meta.xml
<CustomField>
    <fullName>Date_depot_dossier__c</fullName>
    <label>Date dépôt dossier</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Date_Paiement_Facture__c.field-meta.xml
<CustomField>
    <fullName>Date_Paiement_Facture__c</fullName>
    <label>Date Paiement Facture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Decision_Banque__c.field-meta.xml
<CustomField>
    <fullName>Decision_Banque__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attente accord avec OPC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Dossier_d_bloqu__c.field-meta.xml
<CustomField>
    <fullName>Dossier_d_bloqu__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dossier débloqué</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Facture_deposee__c.field-meta.xml
<CustomField>
    <fullName>Facture_deposee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Facture déposée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Facture_Payee__c.field-meta.xml
<CustomField>
    <fullName>Facture_Payee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Facture payée en totalité</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Montant_du_Financement__c.field-meta.xml
<CustomField>
    <fullName>Montant_du_Financement__c</fullName>
    <label>Montant du crédit immo - OB</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Proprietaire__c.field-meta.xml
<CustomField>
    <fullName>Proprietaire__c</fullName>
    <label>Propriétaire</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Stats_Dossiers.cls
public with sharing class Stats_Dossiers{

 public Stats_Dossiers() {

    }
     public Stats_Dossiers(ApexPages.StandardController controller) {

    }
    //dossierDepose Omar
public AggregateResult[] dossierDeposeOmarToday {
        get {
        System.debug('The value is: ');
            return [SELECT  count(Id) depot ,SUM(Montant_du_Financement__c) somme   from Dossier__c where  Date_depot_dossier__c=TODAY and Proprietaire__c ='Omar BENZHA' ];
        }
    }

public AggregateResult[] dossierDeposeOmarYESTERDAY {
        get {
            return [SELECT  count(Id) depot ,SUM(Montant_du_Financement__c) somme   from Dossier__c where  Date_depot_dossier__c=YESTERDAY and Proprietaire__c ='Omar BENZHA' ];
        }
    }
    public AggregateResult[] dossierDeposeOmarTHISWEEK{
        get {
            return [SELECT  count(Id) depot ,SUM(Montant_du_Financement__c) somme   from Dossier__c where  Date_depot_dossier__c=THIS_WEEK and Proprietaire__c ='Omar BENZHA' ];
        }
    }
      public AggregateResult[] dossierDeposeOmarLASTWEEK{
        get {
            return [SELECT  count(Id) depot ,SUM(Montant_du_Financement__c) somme   from Dossier__c where  Date_depot_dossier__c=LAST_WEEK and Proprietaire__c ='Omar BENZHA' ];
        }
    }
      public AggregateResult[] dossierDeposeOmarTHISMONTH{
        get {
            return [SELECT  count(Id) depot ,SUM(Montant_du_Financement__c) somme   from Dossier__c where  Date_depot_dossier__c=THIS_MONTH and Proprietaire__c ='Omar BENZHA' ];
        }
     }
    public AggregateResult[] dossierDeposeOmarLASTMONTH{
        get {
            return [SELECT  count(Id) depot ,SUM(Montant_du_Financement__c) somme   from Dossier__c where  Date_depot_dossier__c=LAST_MONTH and Proprietaire__c ='Omar BENZHA' ];
        }
    }
    public AggregateResult[] dossierDeposeOmarTHISYEAR{
        get {
            return [SELECT  count(Id) depot ,SUM(Montant_du_Financement__c) somme   from Dossier__c where  Date_depot_dossier__c=THIS_YEAR and Proprietaire__c ='Omar BENZHA' ];
        }
    }
    public AggregateResult[] dossierDeposeOmarLASTYEAR{
        get {
            return [SELECT  count(Id) depot ,SUM(Montant_du_Financement__c) somme   from Dossier__c where  Date_depot_dossier__c=LAST_YEAR and Proprietaire__c ='Omar BENZHA' ];
        }
    }
    public AggregateResult[] dossierDeposeOmarALL{
        get {
            return [SELECT  count(Id) depot ,SUM(Montant_du_Financement__c) somme   from Dossier__c where  Proprietaire__c ='Omar BENZHA' ];
        }
    }
    // Dossier Accepter
    
       public AggregateResult[] dossierAccepteOmarTodaY{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_accord_dossier__c=TODAY and Decision_Banque__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
 
       public AggregateResult[] dossierAccepteOmarYESTERDAY{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_accord_dossier__c=YESTERDAY and Decision_Banque__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
     public AggregateResult[] dossierAccepteOmarTHISWEEK{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_accord_dossier__c=THIS_WEEK and Decision_Banque__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
       public AggregateResult[] dossierAccepteOmarLASTWEEK{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_accord_dossier__c=LAST_WEEK and Decision_Banque__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
     public AggregateResult[] dossierAccepteOmarTHISMONTH{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_accord_dossier__c=THIS_MONTH and Decision_Banque__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
     public AggregateResult[] dossierAccepteOmarLASTMONTH{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_accord_dossier__c=LAST_MONTH and Decision_Banque__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
    public AggregateResult[] dossierAccepteOmarTHISYEAR{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_accord_dossier__c=THIS_YEAR and Decision_Banque__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
      public AggregateResult[] dossierAccepteOmarLASTYEAR{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_accord_dossier__c=LAST_YEAR and Decision_Banque__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
    public AggregateResult[] dossierAccepteOmarALL{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Decision_Banque__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
    //Dossier Finances par omar
    public AggregateResult[] dossierFinanceOmarToday{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_deblocage__c=TODAY and Dossier_d_bloqu__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
    
      public AggregateResult[] dossierFinanceOmarYesterday{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_deblocage__c=YESTERDAY and Dossier_d_bloqu__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
    
      public AggregateResult[] dossierFinanceOmarTHISWEEK{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_deblocage__c=THIS_WEEK and Dossier_d_bloqu__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
 public AggregateResult[] dossierFinanceOmarLASTWEEK{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_deblocage__c=LAST_WEEK and Dossier_d_bloqu__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
    
    public AggregateResult[] dossierFinanceOmarTHISMONTH{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_deblocage__c=THIS_MONTH and Dossier_d_bloqu__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
      public AggregateResult[] dossierFinanceOmarLASTMONTH{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_deblocage__c=LAST_MONTH and Dossier_d_bloqu__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
         
      public AggregateResult[] dossierFinanceOmarTHISYEAR{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_deblocage__c=THIS_YEAR and Dossier_d_bloqu__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }
             public AggregateResult[] dossierFinanceOmarLASTYEAR{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where    Date_deblocage__c=LAST_YEAR and Dossier_d_bloqu__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }  
        public AggregateResult[] dossierFinanceOmarALL{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme   from Dossier__c where Dossier_d_bloqu__c=TRUE and  Proprietaire__c ='Omar BENZHA' ];
        }
    }  
    
    // Dossier facturer
     public AggregateResult[] dossierFactureOmarToday{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from Dossier__c where    Date_d_p_t_facture__c=TODAY and Facture_deposee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }  
      public AggregateResult[] dossierFactureOmarYESTERDAY{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from Dossier__c where    Date_d_p_t_facture__c=YESTERDAY and Facture_deposee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }  
      public AggregateResult[] dossierFactureOmarTHISWEEK{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from Dossier__c where    Date_d_p_t_facture__c=THIS_WEEK and Facture_deposee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }  
          public AggregateResult[] dossierFactureOmarLASTWEEK{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from Dossier__c where    Date_d_p_t_facture__c=LAST_WEEK and Facture_deposee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }  
         public AggregateResult[] dossierFactureOmarTHISMONTH{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from Dossier__c where    Date_d_p_t_facture__c=THIS_MONTH and Facture_deposee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }  
        public AggregateResult[] dossierFactureOmarLASTMONTH{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from Dossier__c where    Date_d_p_t_facture__c=LAST_MONTH and Facture_deposee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }  
    public AggregateResult[] dossierFactureOmarTHISYEAR{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from Dossier__c where    Date_d_p_t_facture__c=THIS_YEAR and Facture_deposee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }  
    
        public AggregateResult[] dossierFactureOmarLASTYEAR{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from Dossier__c where    Date_d_p_t_facture__c=LAST_YEAR and Facture_deposee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }  
   public AggregateResult[] dossierFactureOmarALL{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from Dossier__c where    Facture_deposee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }  
//Payes

public AggregateResult[] dossierPayeOmarTODAY{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from  Dossier__c where     Date_Paiement_Facture__c=TODAY and Facture_Payee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }  
public AggregateResult[] dossierPayeOmarYESTERDAY{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from  Dossier__c where     Date_Paiement_Facture__c=YESTERDAY and Facture_Payee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }  

 
public AggregateResult[] dossierPayeOmarTHISWEEK{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from  Dossier__c where     Date_Paiement_Facture__c=THIS_WEEK and Facture_Payee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }  
public AggregateResult[] dossierPayeOmarLASTWEEK{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from  Dossier__c where     Date_Paiement_Facture__c=LAST_WEEK and Facture_Payee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }  
    public AggregateResult[] dossierPayeOmarTHISMONTH{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from  Dossier__c where     Date_Paiement_Facture__c=THIS_MONTH and Facture_Payee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }
     public AggregateResult[] dossierPayeOmarLASTMONTH{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from  Dossier__c where     Date_Paiement_Facture__c=LAST_MONTH and Facture_Payee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
        }
         public AggregateResult[] dossierPayeOmarTHISYEAR{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from  Dossier__c where     Date_Paiement_Facture__c=THIS_YEAR and Facture_Payee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }
        public AggregateResult[] dossierPayeOmarLASTYEAR{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from  Dossier__c where     Date_Paiement_Facture__c=LAST_YEAR and Facture_Payee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }
 public AggregateResult[] dossierPayeOmarALL{
        get {
            return [SELECT  count(Id) accepte ,SUM(Montant_du_Financement__c) somme    from  Dossier__c where     Facture_Payee__c=TRUE and Proprietaire__c  ='Omar BENZHA' ];
        }
    }
    
    
}