force-app/main/default/objects/Dossier__c/Dossier__c.object-meta.xml
<CustomObject>
    <label>Dossier</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>N° de Dossier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dossiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dossier__c/fields/Accord_client_sur_conditions_reserves__c.field-meta.xml
<CustomField>
    <fullName>Accord_client_sur_conditions_reserves__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accord client sur conditions et reserves</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Apporteur__c.field-meta.xml
<CustomField>
    <fullName>Apporteur__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apporteur</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Dossiers (Commercial)</relationshipLabel>
    <relationshipName>Dossiers_Soumis</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Banquier__c.field-meta.xml
<CustomField>
    <fullName>Banquier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Banquier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dossiers (Banquier)</relationshipLabel>
    <relationshipName>DossiersBanquier</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Confirmation_Envoi_l_analyse__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Envoi_l_analyse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirmation Envoi à l&apos;analyse</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/contact__c.field-meta.xml
<CustomField>
    <fullName>contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Dossiers</relationshipLabel>
    <relationshipName>Dossiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Date_depot_dossier__c.field-meta.xml
<CustomField>
    <fullName>Date_depot_dossier__c</fullName>
    <label>Date dépôt dossier</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Date_estim_accord__c.field-meta.xml
<CustomField>
    <fullName>Date_estim_accord__c</fullName>
    <label>Date estimé accord</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Date_Estim_D_blocage__c.field-meta.xml
<CustomField>
    <fullName>Date_Estim_D_blocage__c</fullName>
    <label>Date Estimé Déblocage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Decision_Banque__c.field-meta.xml
<CustomField>
    <fullName>Decision_Banque__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attente accord avec OPC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Decision_banque_re_Retour_charges__c.field-meta.xml
<CustomField>
    <fullName>Decision_banque_re_Retour_charges__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Decision banque re- Retour à charges</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Depot_Banque__c.field-meta.xml
<CustomField>
    <fullName>Depot_Banque__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dépôt Banque P1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Depot_Banque_P2_3__c.field-meta.xml
<CustomField>
    <fullName>Depot_Banque_P2_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dépôt Banque P2et3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Dossier_Complet__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Complet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dossier complet P1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Dossier_complet_P2_3__c.field-meta.xml
<CustomField>
    <fullName>Dossier_complet_P2_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dossier complet P2et3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Dossier_Constitue_P1__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Constitue_P1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dossier Constitué P1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Dossier_Constitue_P2_3__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Constitue_P2_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dossier Constitué P2et3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Dossier_d_bloqu__c.field-meta.xml
<CustomField>
    <fullName>Dossier_d_bloqu__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dossier débloqué</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Dossier_debloque_systeme_banque__c.field-meta.xml
<CustomField>
    <fullName>Dossier_debloque_systeme_banque__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dossier débloqué système banque</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Env_acc_sign_cach_ou_OPC_not__c.field-meta.xml
<CustomField>
    <fullName>Env_acc_sign_cach_ou_OPC_not__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Env de l&apos;acc sign cach ou l&apos;OPC au not</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Env_contr_pret_signes_leg_bq__c.field-meta.xml
<CustomField>
    <fullName>Env_contr_pret_signes_leg_bq__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Env des contr de prêt signés leg à la bq</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Env_cp_contr_not_pour_ed_min__c.field-meta.xml
<CustomField>
    <fullName>Env_cp_contr_not_pour_ed_min__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Env copie contr au not pour l&apos;éd de min</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Env_min_serv_jur_via_ag_pour_val__c.field-meta.xml
<CustomField>
    <fullName>Env_min_serv_jur_via_ag_pour_val__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Env min au serv jur(via ag)pour val</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Envoi_des_conditions1_au_client__c.field-meta.xml
<CustomField>
    <fullName>Envoi_des_conditions1_au_client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Envoi des conditions 1 au client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Envoi_des_conditions2_au_client__c.field-meta.xml
<CustomField>
    <fullName>Envoi_des_conditions2_au_client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Envoi des conditions 2 au client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Exemplaires_docs_envoyes_au_client__c.field-meta.xml
<CustomField>
    <fullName>Exemplaires_docs_envoyes_au_client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exemplaires de docs envoyés au client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Expertise_du_bien_non_requise__c.field-meta.xml
<CustomField>
    <fullName>Expertise_du_bien_non_requise__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expertise du bien non requise</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Expertise_du_bien_realisee__c.field-meta.xml
<CustomField>
    <fullName>Expertise_du_bien_realisee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expertise du bien réalisée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Expertise_du_bien_requise__c.field-meta.xml
<CustomField>
    <fullName>Expertise_du_bien_requise__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expertise du bien requise</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Facture_deposee__c.field-meta.xml
<CustomField>
    <fullName>Facture_deposee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Facture déposée</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Lettre_accompagnement_fourni_client__c.field-meta.xml
<CustomField>
    <fullName>Lettre_accompagnement_fourni_client__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lettre d&apos;accompagnement fourni au client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Levee_des_reserves__c.field-meta.xml
<CustomField>
    <fullName>Levee_des_reserves__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Levée des reserves</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Min_renv_not_par_serv_jur__c.field-meta.xml
<CustomField>
    <fullName>Min_renv_not_par_serv_jur__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Min renv au not par le serv jur</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Minute_validee_par_service_juridique__c.field-meta.xml
<CustomField>
    <fullName>Minute_validee_par_service_juridique__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Minute validée par le service juridique1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Nom_du_co_emprunteur__c.field-meta.xml
<CustomField>
    <fullName>Nom_du_co_emprunteur__c</fullName>
    <formula>contact__r.Nom_du_co_emprunteur__r.FirstName &amp;&apos; &apos;&amp; contact__r.Nom_du_co_emprunteur__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nom du co-emprunteur</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Notaire__c.field-meta.xml
<CustomField>
    <fullName>Notaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notaire</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Dossiers (Notaire)</relationshipLabel>
    <relationshipName>Dossiers_notaire</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Pieces_manquantes_P1__c.field-meta.xml
<CustomField>
    <fullName>Pieces_manquantes_P1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pièces manquantes P1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Pieces_manquantes_P2_3__c.field-meta.xml
<CustomField>
    <fullName>Pieces_manquantes_P2_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pièces manquantes P2et3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/RDV_Ouverture_de_compte_programme__c.field-meta.xml
<CustomField>
    <fullName>RDV_Ouverture_de_compte_programme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RDV Ouverture de compte programmé</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/RDV_pris_visite_medicale__c.field-meta.xml
<CustomField>
    <fullName>RDV_pris_visite_medicale__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RDV pris visite medicale</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Reponse_assurance_recue__c.field-meta.xml
<CustomField>
    <fullName>Reponse_assurance_recue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Réponse assurance reçue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Retour_a_charges__c.field-meta.xml
<CustomField>
    <fullName>Retour_a_charges__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retour à charges</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Sign_min_par_bq_vend_ach_dev_not__c.field-meta.xml
<CustomField>
    <fullName>Sign_min_par_bq_vend_ach_dev_not__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sign min par la bq le vend l&apos;ach dev not</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Signature_Assurances__c.field-meta.xml
<CustomField>
    <fullName>Signature_Assurances__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Signature Assurances</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Signature_de_OPC__c.field-meta.xml
<CustomField>
    <fullName>Signature_de_OPC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Signature de l&apos;OPC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Simulation__c.field-meta.xml
<CustomField>
    <fullName>Simulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Simulation</label>
    <referenceTo>Simulation__c</referenceTo>
    <relationshipLabel>Dossiers</relationshipLabel>
    <relationshipName>Dossiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Super_apporteur_Dossier__c.field-meta.xml
<CustomField>
    <fullName>Super_apporteur_Dossier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Super apporteur_Dossier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dossiers (Super apporteur)</relationshipLabel>
    <relationshipName>DossiersSuperApporteur</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Super_banquier__c.field-meta.xml
<CustomField>
    <fullName>Super_banquier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Super banquier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dossiers (Super banquier)</relationshipLabel>
    <relationshipName>Dossiers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Transmettre_Dossier_l_agence__c.field-meta.xml
<CustomField>
    <fullName>Transmettre_Dossier_l_agence__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dossier Accordé avec OPC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/VEFA_caution_bq_remise_bq_prom__c.field-meta.xml
<CustomField>
    <fullName>VEFA_caution_bq_remise_bq_prom__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VEFA caution bq remise par bq du prom</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Virement_du_premier_salaire_domicile__c.field-meta.xml
<CustomField>
    <fullName>Virement_du_premier_salaire_domicile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Virement du premier salaire domicile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TR002_Dossier_Test.cls
@isTest
public with sharing class TR002_Dossier_Test {
    
    @testSetup static void testSetup(){
        /* CUSTOM SETTING NOTIFICATION*/

		Notifications__c notifEmailParam = New Notifications__c();
		notifEmailParam.Activee__c = true;
		notifEmailParam.Subject__c = 'test';
		notifEmailParam.SenderDisplayName__c = 'Test';
		notifEmailParam.ReplyTo__c = 'test@test.com';
		notifEmailParam.ccAddresses__c = 'test@test.com';
		insert notifEmailParam;

		/* ACCOUNT */
		Account account = new Account();
		account.Name = 'Test Account';
		account.Email__c = 'test.account@test.com';
		
		insert account;

		/* CO-EMPRUNTEUR */
		Contact coemprunteur = new Contact();
		coemprunteur.lastName = 'coemprunteurTest';
		coemprunteur.Email = 'coemprunteurtest@test.com';

		insert coemprunteur;

		/* CONTACT */
		Contact contact = new Contact();
		contact.lastName = 'contactTest';
		contact.accountId = account.Id;
		contact.Email = 'contacttest@test.com';
		contact.Nom_du_co_emprunteur__c = coemprunteur.Id;
		
		insert contact;

		/* SUPER BANQUIER */
		Account superBanquier = new Account();
		superBanquier.Name = 'Test Super Banquier';
		superBanquier.Type = 'Banque';
		superBanquier.Email__c = 'testsuperbanquier@test.com';

		insert superBanquier;

		/* BANQUIER */
		Account banquier = new Account();
		banquier.Name = 'Test Banquier';
		banquier.Type = 'Banque';
		banquier.Email__c = 'testbanquier@test.com';

		insert banquier;


		/* NOTAIRE */
		Contact notaire = new Contact();
		notaire.lastName = 'notaireTest';
		notaire.Email = 'notairetest@test.com';
		
		insert notaire;

		/* SUPER APPORTEUR */
		Account superApporteur = new Account();
		superApporteur.Name = 'Test Super Apporteur';
		superApporteur.Email__c = 'testsuperapporteur@test.com';

		insert superApporteur;

		/* APPORTEUR */
		Contact apporteur = new Contact();
		apporteur.lastName = 'apporteurTest';
		apporteur.Email = 'apporteurTest@test.com';

		insert apporteur;
        
        Simulation__c simulation = new Simulation__c();
        simulation.Actif__c = TRUE;
        simulation.Contact__c = contact.Id;
        simulation.MCI_Sim_ID__c = '1234';
        // Sim Hot
        simulation.Statut__c = 'Qualifié';
        simulation.Resultat__c = 'Trouvé le bien-AFD';
        simulation.Motif__c = 'Shopping';
        insert simulation;

		/* DOSSIER */
		Dossier__c dossier = new Dossier__c();
		dossier.contact__c = contact.Id;
        dossier.Simulation__c = simulation.Id;
        dossier.Dossier_Constitue_P1__c = True;
		dossier.Super_banquier__c = superBanquier.Id;
		dossier.Banquier__c = banquier.Id;
		dossier.Notaire__c = notaire.Id;
		dossier.Super_apporteur_Dossier__c = superApporteur.Id;
		dossier.Apporteur__c = apporteur.Id;
		dossier.Date_estim_accord__c = System.Today().addDays(10);
		dossier.Date_depot_dossier__c = SYstem.Today();
		dossier.Date_Estim_D_blocage__c = System.Today().addDays(15);

		insert dossier;

    }
        
	@isTest static void testUpdateDossier(){

		
		Dossier__c dossierInserted = [Select Id From Dossier__c LIMIT 1];
		Dossier__c dossier = new Dossier__c();
        dossier.Id = dossierInserted.Id;
		dossier.Dossier_Constitue_P1__c = true;
		dossier.Depot_Banque__c = true;
        dossier.Confirmation_Envoi_l_analyse__c = true;
		dossier.Pieces_manquantes_P1__c = true;
		dossier.Dossier_Complet__c = true;
		dossier.Expertise_du_bien_non_requise__c = true;
		dossier.Expertise_du_bien_requise__c = true;
		dossier.Expertise_du_bien_realisee__c = true;
		dossier.Decision_Banque__c = true;
		dossier.Transmettre_Dossier_l_agence__c = true;
        dossier.Envoi_des_conditions1_au_client__c = true;
        dossier.Retour_a_charges__c = true;
        dossier.Decision_banque_re_Retour_charges__c = true;
        dossier.Envoi_des_conditions2_au_client__c = true;
        dossier.Accord_client_sur_conditions_reserves__c = true;
		dossier.RDV_Ouverture_de_compte_programme__c = true;
        dossier.Signature_de_OPC__c = true;
		dossier.Signature_Assurances__c = true;
		dossier.Exemplaires_docs_envoyes_au_client__c = true;
        dossier.RDV_pris_visite_medicale__c = true;
		dossier.Lettre_accompagnement_fourni_client__c = true;
		dossier.Reponse_assurance_recue__c = true;
		dossier.Dossier_Constitue_P2_3__c = true;
		dossier.Depot_Banque_P2_3__c = true;
		dossier.Pieces_manquantes_P2_3__c  = true;
		dossier.Dossier_complet_P2_3__c  = true;
        dossier.Virement_du_premier_salaire_domicile__c = true;
        dossier.Env_acc_sign_cach_ou_OPC_not__c = true;
		dossier.VEFA_caution_bq_remise_bq_prom__c = true;
        dossier.Levee_des_reserves__c = true;
		dossier.Env_contr_pret_signes_leg_bq__c = true;
        dossier.Env_cp_contr_not_pour_ed_min__c = true;
		dossier.Env_min_serv_jur_via_ag_pour_val__c = true;
        dossier.Minute_validee_par_service_juridique__c = true;
		dossier.Min_renv_not_par_serv_jur__c = true;
		dossier.Dossier_debloque_systeme_banque__c = true;
		dossier.Sign_min_par_bq_vend_ach_dev_not__c = true;
		dossier.Dossier_d_bloqu__c = true;
		dossier.Facture_deposee__c = true;
        dossier.Facture_validee__c = true;
		dossier.Facture_avancee__c = true;
		dossier.Facture_Payee_global__c = true;
		dossier.Facture_Payee__c = true;
		dossier.Facture_payee_en_partie__c = true;

		dossier.Compte_Bancaire_Ouvert__c = true;
		dossier.RDV_Visite_M_dicale__c = true;
		dossier.Lettre_d_engagement_notaire_chez_Banque__c = true;
		dossier.Edition_du_contrat_de_pr_t__c = true;
		dossier.Contrat_l_galis_transmis_par_client__c = true;
		dossier.Minute_tablie_par_le_notaire__c = true;
		dossier.Cheque_Banque_remis_au_notaire__c = true;
		dossier.Dossier_Perdu__c = true;
		dossier.RDV_Ouverture_de_compte__c = true;


		update dossier;

		/*dossier = [SELECT D_Dossier_debloque_systeme_banque__c, D_Confirmation_Envoi_l_analyse__c  FROM Dossier__c WHERE Id =: dossier.Id];
		system.assertEquals(dossier.D_Dossier_debloque_systeme_banque__c , Date.Today());*/

		
        
        Test.startTest();
        // UPDATE DATE
		dossier.D_Confirmation_Envoi_l_analyse__c = Date.Today().addDays(-3);
		update dossier;
		Test.stopTest();
        
		dossier = [SELECT D_Dossier_debloque_systeme_banque__c, D_Confirmation_Envoi_l_analyse__c  FROM Dossier__c WHERE Id =: dossier.Id];
		system.assertEquals(dossier.D_Confirmation_Envoi_l_analyse__c, Date.Today().addDays(-3));
		system.assertEquals(dossier.D_Dossier_debloque_systeme_banque__c, Date.Today());

	}
}