force-app/main/default/objects/Dossier__c/Dossier__c.object-meta.xml
<CustomObject>
    <label>Dossier</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>N° de Dossier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dossiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dossier__c/fields/contact__c.field-meta.xml
<CustomField>
    <fullName>contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Dossiers</relationshipLabel>
    <relationshipName>Dossiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Date_depot_dossier__c.field-meta.xml
<CustomField>
    <fullName>Date_depot_dossier__c</fullName>
    <label>Date dépôt dossier</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Date_estim_accord__c.field-meta.xml
<CustomField>
    <fullName>Date_estim_accord__c</fullName>
    <label>Date estimé accord</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Date_Estim_D_blocage__c.field-meta.xml
<CustomField>
    <fullName>Date_Estim_D_blocage__c</fullName>
    <label>Date Estimé Déblocage</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Dossier_Constitue_P1__c.field-meta.xml
<CustomField>
    <fullName>Dossier_Constitue_P1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dossier Constitué P1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/MCI_User_ID__c.field-meta.xml
<CustomField>
    <fullName>MCI_User_ID__c</fullName>
    <formula>contact__r.MCI_User_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MCI User ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Simulation__c.field-meta.xml
<CustomField>
    <fullName>Simulation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Simulation</label>
    <referenceTo>Simulation__c</referenceTo>
    <relationshipLabel>Dossiers</relationshipLabel>
    <relationshipName>Dossiers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WS_PushDossiersToWebsite_Test.cls
@isTest
public with sharing class WS_PushDossiersToWebsite_Test {
    @isTest
    public static void WS_PushDossiersToWebsite_Test() {

        /* ACCOUNT */
		Account account = new Account();
		account.Name = 'Test Account';
		account.Email__c = 'test.account@test.com';
		insert account;
        /* CONTACT */
		Contact contact = new Contact();
		contact.lastName = 'contactTest';
		contact.accountId = account.Id;
		contact.Email = 'contacttest@test.com';
        contact.MCI_User_ID__c='1234';		
		insert contact;
        
        Simulation__c simulation = new Simulation__c();
        simulation.Actif__c = TRUE;
        simulation.Contact__c = contact.Id;
        simulation.MCI_Sim_ID__c = '1234';
        // Sim Hot
        simulation.Statut__c = 'Qualifié';
        simulation.Resultat__c = 'Trouvé le bien-AFD';
        simulation.Motif__c = 'Shopping';
        insert simulation;

        /* DOSSIER */
		Dossier__c dossier = new Dossier__c();
		dossier.contact__c = contact.Id;
        dossier.Simulation__c = simulation.Id;
        dossier.Dossier_Constitue_P1__c = True;
		dossier.Date_estim_accord__c = System.Today().addDays(10);
		dossier.Date_depot_dossier__c = SYstem.Today();
		dossier.Date_Estim_D_blocage__c = System.Today().addDays(15);

		insert dossier;

        Test.startTest();
        Set <Id> dossiersIds = new set<Id>();
        List<dossier__c> dossiers = [select id from dossier__c];
        for(dossier__c dossier2 :dossiers){
            dossiersIds.add(dossier2.Id);
        }
        WS_PushDossiersToWebsite.ws_PushDataDossiersToWebsite(dossiersIds);

        Test.stopTest();

    }
}