force-app/main/default/objects/Dossier__c/Dossier__c.object-meta.xml
<CustomObject>
    <label>Dossier</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>N° de Dossier</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dossiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Dossier__c/fields/Commission_parrain_MCI__c.field-meta.xml
<CustomField>
    <fullName>Commission_parrain_MCI__c</fullName>
    <formula>(
IF(ISBLANK( Parrain_auto_filled__c),0,
com_Brut_en_V_HT_SOS__c * 0.5)
)</formula>
    <label>Commission parrain MCI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Etape_Actuelle__c.field-meta.xml
<CustomField>
    <fullName>Etape_Actuelle__c</fullName>
    <label>Etape Actuelle</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/MCI_User_ID__c.field-meta.xml
<CustomField>
    <fullName>MCI_User_ID__c</fullName>
    <formula>contact__r.MCI_User_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MCI User ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Montant_du_Financement__c.field-meta.xml
<CustomField>
    <fullName>Montant_du_Financement__c</fullName>
    <label>Montant du crédit immo - OB</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dossier__c/fields/Parrain_paye_impaye__c.field-meta.xml
<CustomField>
    <fullName>Parrain_paye_impaye__c</fullName>
    <label>Parrain payé/impayé</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dossier en cours</fullName>
                <default>true</default>
                <label>Dossier en cours</label>
            </value>
            <value>
                <fullName>Paiement en cours</fullName>
            </value>
            <value>
                <fullName>Payé</fullName>
            </value>
            <value>
                <fullName>Impayé</fullName>
                <isActive>false</isActive>
                <label>Impayé</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WS_PushDossiersToWebsite.cls
public without sharing class WS_PushDossiersToWebsite {
    @future (callout=true)
	public static void ws_PushDataDossiersToWebsite(Set <Id> dossiersIds) {
		String response;

		// INSTANCIATE A NEW HTTP OBJECT
		Http h = new Http();
		// INSTANCIATE A NEW HTTP RESQUEST
		HttpRequest req = new HttpRequest();
        req.setEndpoint(Label.backEndEndPoint+'/update-documents');
		req.setMethod('POST');
		req.setHeader('Content-Type', 'application/json');
		req.setHeader('Accept', 'application/json');
		req.setTimeout(120000);
		
		
		system.debug('req' + req);
        // build JSON data
        Dossier_CPI dossierCPI = new Dossier_CPI();
        dossierCPI.sales_token = Label.backEndToken;
        List<Data_CPI> datasCPI = new List<Data_CPI>();
        List<dossier__c> dossiers = [SELECT Id,createdDate,Name,Montant_du_Financement__c,Etape_Actuelle__c,
                                     Commission_parrain_MCI__c,Parrain_paye_impaye__c,MCI_User_ID__c 
                                     FROM dossier__c WHERE Id IN :dossiersIds];
        for(Dossier__c dossier :dossiers){
            if(dossier.MCI_User_ID__c != null){
                Data_CPI dataCPI = new Data_CPI();
                dataCPI.dossier_created_at = String.valueOf(dossier.createdDate);
                dataCPI.dossier_sforce_number = Integer.valueOf(dossier.Name.split('-')[1]);
                dataCPI.dossier_sforce_montant_credit = dossier.Montant_du_Financement__c;
                dataCPI.dossier_state = dossier.Etape_Actuelle__c;
                dataCPI.dossier_montant_commission_parrain = dossier.Commission_parrain_MCI__c;
                dataCPI.dossier_statut_commission_parrain = dossier.Parrain_paye_impaye__c;
                dataCPI.dossier_document_id = dossier.Id;
                dataCPI.user_id = Integer.valueOf(dossier.MCI_User_ID__c);
                datasCPI.add(dataCPI);
            }
            
        }
        
        if(datasCPI.size()>0){
            dossierCPI.data = datasCPI;
            String JSON_File = JSON.serialize(dossierCPI);
            req.setBody(JSON_File);
            // SEND THE REQUEST AND RETURN A RESPONSE
            if(!Test.isRunningTest()){
                HttpResponse res = h.send(req);
                system.debug('res' + res);
            }
        }   
	}

	public class Dossier_CPI {
		public String sales_token;
		public List<Data_CPI> data;
	}

	public class Data_CPI {
		public String dossier_created_at;
		public Integer dossier_sforce_number;
		public Decimal dossier_sforce_montant_credit;
		public String dossier_state;
		public Decimal dossier_montant_commission_parrain;
		public String dossier_statut_commission_parrain;
		public String dossier_document_id;
		public Integer user_id;
	}
}